// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH-MT0YE1rP31_AzkevYJHERsAcMQxNXw',
    appId: '1:224634000410:web:81dec757143910d68cada3',
    messagingSenderId: '224634000410',
    projectId: 'cinebooking-tim5',
    authDomain: 'cinebooking-tim5.firebaseapp.com',
    storageBucket: 'cinebooking-tim5.firebasestorage.app',
    measurementId: 'G-4NTC30QFKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNiXZJfgu6MUR1KIBaYd26rBSvpgjyCf4',
    appId: '1:224634000410:android:a66e7c05b0fc565b8cada3',
    messagingSenderId: '224634000410',
    projectId: 'cinebooking-tim5',
    storageBucket: 'cinebooking-tim5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHCZyGPWcBccJnxNr6H-o5T7JwQ4YQEUs',
    appId: '1:224634000410:ios:967b5fa7146ffa9d8cada3',
    messagingSenderId: '224634000410',
    projectId: 'cinebooking-tim5',
    storageBucket: 'cinebooking-tim5.firebasestorage.app',
    iosBundleId: 'com.example.cinebookingKelompok5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHCZyGPWcBccJnxNr6H-o5T7JwQ4YQEUs',
    appId: '1:224634000410:ios:967b5fa7146ffa9d8cada3',
    messagingSenderId: '224634000410',
    projectId: 'cinebooking-tim5',
    storageBucket: 'cinebooking-tim5.firebasestorage.app',
    iosBundleId: 'com.example.cinebookingKelompok5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH-MT0YE1rP31_AzkevYJHERsAcMQxNXw',
    appId: '1:224634000410:web:ba263599e262f8b68cada3',
    messagingSenderId: '224634000410',
    projectId: 'cinebooking-tim5',
    authDomain: 'cinebooking-tim5.firebaseapp.com',
    storageBucket: 'cinebooking-tim5.firebasestorage.app',
    measurementId: 'G-DDDSJDCWXR',
  );
}
